Validation for columns order
keboola/google-bigquery-writer pull request #11
Opened 2018-07-10 15:27 UTC by Actimel

Solve #10

2018-07-11 13:26 UTC, ondrejhlavacek commented on google_bigquery_writer/schema_mapper.py
> +    csv_reader = csv.reader(csvfile, delimiter=',', quotechar='"')
tady by bylo asi lepší získat sloupce tabulky z manifestu, měly by bejt ve stejným pořadí jako v souboru. pokud ne, bude to chyba ve Storage nebo Docker Runneru

2018-07-11 13:39 UTC, ondrejhlavacek requested changes
použil bych manifest místo načítání hlavičky z CSV, jinak dobrý
mmch neříkal jsi, že jsi zkoušel novější verzi bigquery knihovny? vidím to furt locklý na 0.24

2018-07-11 16:07 UTC, Actimel commented on google_bigquery_writer/schema_mapper.py
> +    csv_reader = csv.reader(csvfile, delimiter=',', quotechar='"')
Ok, upravim to.

2018-07-11 16:09 UTC, Actimel commented
Ano zkousel jsem to, hlavne ale kvuli streamovanemu zapisu, ten nakonec nutny nebyl, tak jsem to revertnul vse. Nicmene, kdyz uz tam problem neni, tak to muzeme nechat na te nejaktualnejsi verzi 👍

2018-07-11 18:30 UTC, Actimel commented
S tou verzi to je ma chyba, testy stale neprochazeji. Nechal jsem se osalit tim, ze jsem nespustil build 🤦‍♂️

2018-07-12 15:29 UTC, ondrejhlavacek commented
Rebasnul jsem branch

2018-07-13 12:16 UTC, ondrejhlavacek commented on google_bigquery_writer/schema_mapper.py
> +    return json.load(manifest_file)['columns']
promiň, ještě jsem ti zapomněl říct, že pro práci s manifestem máme pythonovskou knihovnu (měla by tam už být i importovaná) - https://developers.keboola.com/extend/component/implementation/python/#using-kbc-package

2018-07-13 12:18 UTC, ondrejhlavacek commented on test/test_schema_mapper.py
> +            assert str(err) == "Unexpected column order in configuration. Actual: col1, col2, expected: col2, col1."
Co takhle?
`Column order mismatch: CSV: col1, col2, BigQuery: col2, col1.` Nebo místo CSV použít configuration, to je asi jedno.

2018-07-16 07:41 UTC, ondrejhlavacek approved these changes
lgtm

2018-07-16 07:49 UTC, merged